### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by simra** [trc492/Frc2019DestinationDeepSpace#5]
I seem to be working with the wrong SparkMax class files.  Do I need to do something special to either update the expected version or download the right jar file?

````
bad class file: C:\GitHub\Frc2019DestinationDeepSpace\robot\libs\SparkMax-java-1.1.3.jar(com/revrobotics/CANDigitalInput.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
````

**Comment by trc492** [comment]
Hmm, my version is also 1.1.3 but I don't have issues building. You may want to clean the project and rebuild everything to see if it fixes it. Also, search the repo tree to see if you have a duplicated jar somewhere else. It is kind of confusing because there is a <RepoRoot>\lib and also a <RepoRoot>\robot\libs. There is yet another lib in your <UserRoot>\wpilib\user\java\lib. So make sure the right lib is in the right place.

BTW Abhay, why did you put SparkMax lib in robot\lib. SparkMax is third party, shouldn't it go to the same place as CTRE lib?

- Michael Tsang

________________________________

**Comment by abhaybd** [comment]
@simra how are you building the project? If it's through terminal, it may be because you're building with Java 8 instead of Java 11. In terminal, type `frcvars2019` and then build with `gradlew :robot:build`

**Comment by abhaybd** [comment]
@trc492 The SparkMax lib is in robot/lib because the traditional method of getting dependencies (via vendorlibs json file) doesn't work for the 1.1.26 beta version. Because of that, I had to supply the jar file, and add it to build.gradle as a local dependency.

Also, the \<UserRoot>\wpilib\user\java\lib is no longer being used by any 2019 project. All dependencies are managed on a project-by-project basis. That means that the contents of that file shouldn't affect any 2019 project. Also, I don't see any \<RepoRoot>\lib folder, what are its contents on your machine?

**Comment by simra** [comment]
In my case I'm using the openjdk 1.8.    I don't see a script named frcvars2019.

**Comment by simra** [comment]
Ah, I see that's part of the FRC toolchain. Looks like I should fix my environment first.

**Comment by abhaybd** [comment]
@simra It should be in the path as installed by the WPILib installer. Does the command fail?

**Comment by DrDab** [comment]
@simra I'm likely a bit late to this issue, but I think that your JDK version is too old. The project configuration requires JDK 11 to build. https://openjdk.java.net/projects/jdk/11/

**Comment by simra** [comment]
Thanks Victor, yes I updated to jdk 11 and everything builds now.
